image_components:
  defaults:
    breakpoints:
      xs: 320
      sm: 640
      md: 768
      lg: 1024
      xl: 1280
      2xl: 1536
    format: "webp"
    quality: 80
    lazy: true
    priority: false
    preload: false
    fit: "cover"
    focal: "center"
    placeholder: "none"
    placeholder-color: null
  cache_dir: "%kernel.project_dir%/public/media/cache"
