services:
  YourVendor\ResponsiveImageBundle\Twig\Components\ResponsiveImage:
    arguments:
      $imageManager: '@Intervention\Image\ImageManager'
      $preloadManager: '@YourVendor\ResponsiveImageBundle\Service\PreloadManager'
    tags: ["twig.component"]

  YourVendor\ResponsiveImageBundle\Service\PreloadManager:
    public: true

  YourVendor\ResponsiveImageBundle\Twig\ResponsiveImageExtension:
    arguments:
      $preloadManager: '@YourVendor\ResponsiveImageBundle\Service\PreloadManager'
    tags: ["twig.extension"]

  Intervention\Image\ImageManager:
    arguments:
      - driver: "gd" # or 'imagick'
