parameters:
  env(CLOUDINARY_URL): "https://res.cloudinary.com/your-cloud-name/image/upload"
  env(FASTLY_URL): "https://www.fastly.io"

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Ommax\ResponsiveImageBundle\:
    resource: "../../*"
    exclude:
      - "../../DependencyInjection/"
      - "../../Resources/"
      - "../../Tests/"

  responsive_image.provider_registry:
    class: Ommax\ResponsiveImageBundle\Provider\ProviderRegistry
    public: true
    arguments:
      $defaultProvider: "%responsive_image.provider%"

  Ommax\ResponsiveImageBundle\Provider\ProviderRegistry: "@responsive_image.provider_registry"

  Ommax\ResponsiveImageBundle\Twig\Components\Img:
    tags: ["twig.component"]

  Ommax\ResponsiveImageBundle\Twig\Components\Picture:
    tags: ["twig.component"]

  Ommax\ResponsiveImageBundle\Service\PreloadManager:
    public: true

  Ommax\ResponsiveImageBundle\Twig\Extension\ResponsiveImageExtension:
    tags: ["twig.extension"]

  Ommax\ResponsiveImageBundle\Provider\LiipImagineProvider:
    arguments:
      $cacheManager: "@liip_imagine.cache.manager"
      $config:
        default_filter: "default"
    tags:
      - { name: "responsive_image.provider" }
