services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Ommax\ResponsiveImageBundle\:
    resource: "../../*"
    exclude:
      - "../../DependencyInjection/"
      - "../../Resources/"
      - "../../Tests/"

  responsive_image.provider_registry:
    class: Ommax\ResponsiveImageBundle\Provider\ProviderRegistry
    public: true

  Ommax\ResponsiveImageBundle\Twig\Components\Img:
    tags: ["twig.component"]

  Ommax\ResponsiveImageBundle\Twig\Components\Picture:
    tags: ["twig.component"]
